name: Build and Push Docker Image

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  DOCKER_IMAGE: alaeddineabdessalem/infrabot

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ env.BRANCH_NAME }}
            ${{ env.BRANCH_NAME == 'main' && format('{0}:latest', env.DOCKER_IMAGE) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
